SIM_DURATION         = 3
N_NANO_SECS          = 500000
NOF_WORKERS          = 4
NOF_USERS            = 800
NOF_WK_SEATS_PRIMI   = 10
NOF_WK_SEATS_SECONDI = 10
NOF_WK_SEATS_COFFEE  = 10
NOF_WK_SEATS_CASSA   = 10
NOF_TABLE_SEATS      = 10
AVG_SRVC_PRIMI       = 10
AVG_SRVC_SECONDI     = 10
AVG_SRVC_COFFEE      = 5
AVG_SRVC_CASSA       = 5
AVG_REFILL_PRIMI     = 50
AVG_REFILL_SECONDI   = 50
MAX_PORZIONI_PRIMI   = 100
MAX_PORZIONI_SECONDI = 100
NOF_PAUSE            = 0
PRICE_PRIMI          = 4.50
PRICE_SECONDI        = 5.50
PRICE_COFFEE         = 1.20
OVERLOAD_THRESHOLD   = 1
MENU_FILE            = conf/menu.txt
