SIM_DURATION         = 3
N_NANO_SECS          = 500000
NOF_WORKERS          = 4
NOF_USERS            = 10
NOF_WK_SEATS_PRIMI   = 5
NOF_WK_SEATS_SECONDI = 5
NOF_WK_SEATS_COFFEE  = 5
NOF_WK_SEATS_CASSA   = 5
NOF_TABLE_SEATS      = 5
AVG_SRVC_PRIMI       = 1
AVG_SRVC_SECONDI     = 1
AVG_SRVC_COFFEE      = 1
AVG_SRVC_CASSA       = 1
AVG_REFILL_PRIMI     = 10
AVG_REFILL_SECONDI   = 10
MAX_PORZIONI_PRIMI   = 20
MAX_PORZIONI_SECONDI = 20
NOF_PAUSE            = 2
PRICE_PRIMI          = 4.50
PRICE_SECONDI        = 5.50
PRICE_COFFEE         = 1.20
OVERLOAD_THRESHOLD   = 999
MENU_FILE            = conf/menu.txt
