# Stress Test 4: FAST SIMULATION
# N_NANO_SECS bassissimo per accelerare enormemente il tempo
# simulato. Espone race conditions temporali.
SIM_DURATION         = 5
N_NANO_SECS          = 10000
NOF_WORKERS          = 10
NOF_USERS            = 30
NOF_WK_SEATS_PRIMI   = 3
NOF_WK_SEATS_SECONDI = 3
NOF_WK_SEATS_COFFEE  = 2
NOF_WK_SEATS_CASSA   = 2
NOF_TABLE_SEATS      = 10
AVG_SRVC_PRIMI       = 3
AVG_SRVC_SECONDI     = 4
AVG_SRVC_COFFEE      = 2
AVG_SRVC_CASSA       = 2
AVG_REFILL_PRIMI     = 10
AVG_REFILL_SECONDI   = 10
MAX_PORZIONI_PRIMI   = 20
MAX_PORZIONI_SECONDI = 20
NOF_PAUSE            = 3
PRICE_PRIMI          = 4.50
PRICE_SECONDI        = 5.50
PRICE_COFFEE         = 1.20
OVERLOAD_THRESHOLD   = 999
MENU_FILE            = conf/menu.txt
