# Stress Test 3: EDGE CASES
# 0 porzioni iniziali primi, 1 utente, 1 operatore.
# Testa condizioni limite: nessun cibo disponibile.
SIM_DURATION         = 1
N_NANO_SECS          = 500000
NOF_WORKERS          = 4
NOF_USERS            = 1
NOF_WK_SEATS_PRIMI   = 1
NOF_WK_SEATS_SECONDI = 1
NOF_WK_SEATS_COFFEE  = 1
NOF_WK_SEATS_CASSA   = 1
NOF_TABLE_SEATS      = 1
AVG_SRVC_PRIMI       = 1
AVG_SRVC_SECONDI     = 1
AVG_SRVC_COFFEE      = 1
AVG_SRVC_CASSA       = 1
AVG_REFILL_PRIMI     = 0
AVG_REFILL_SECONDI   = 0
MAX_PORZIONI_PRIMI   = 0
MAX_PORZIONI_SECONDI = 0
NOF_PAUSE            = 0
PRICE_PRIMI          = 4.50
PRICE_SECONDI        = 5.50
PRICE_COFFEE         = 1.20
OVERLOAD_THRESHOLD   = 999
MENU_FILE            = conf/menu.txt
