# Stress Test 5: MULTI-DAY ENDURANCE
# 15 giorni di simulazione per testare accumulo e reset.
SIM_DURATION         = 15
N_NANO_SECS          = 100000
NOF_WORKERS          = 10
NOF_USERS            = 20
NOF_WK_SEATS_PRIMI   = 3
NOF_WK_SEATS_SECONDI = 3
NOF_WK_SEATS_COFFEE  = 2
NOF_WK_SEATS_CASSA   = 2
NOF_TABLE_SEATS      = 15
AVG_SRVC_PRIMI       = 3
AVG_SRVC_SECONDI     = 4
AVG_SRVC_COFFEE      = 2
AVG_SRVC_CASSA       = 2
AVG_REFILL_PRIMI     = 15
AVG_REFILL_SECONDI   = 15
MAX_PORZIONI_PRIMI   = 30
MAX_PORZIONI_SECONDI = 30
NOF_PAUSE            = 2
PRICE_PRIMI          = 4.50
PRICE_SECONDI        = 5.50
PRICE_COFFEE         = 1.20
OVERLOAD_THRESHOLD   = 999
MENU_FILE            = conf/menu.txt
