# Stress Test 2: EXTREME SCALE
# 200 utenti, 50 operatori. Massimo stress su IPC e fork.
SIM_DURATION         = 2
N_NANO_SECS          = 500000
NOF_WORKERS          = 50
NOF_USERS            = 200
NOF_WK_SEATS_PRIMI   = 15
NOF_WK_SEATS_SECONDI = 15
NOF_WK_SEATS_COFFEE  = 10
NOF_WK_SEATS_CASSA   = 10
NOF_TABLE_SEATS      = 50
AVG_SRVC_PRIMI       = 3
AVG_SRVC_SECONDI     = 4
AVG_SRVC_COFFEE      = 2
AVG_SRVC_CASSA       = 1
AVG_REFILL_PRIMI     = 30
AVG_REFILL_SECONDI   = 30
MAX_PORZIONI_PRIMI   = 60
MAX_PORZIONI_SECONDI = 60
NOF_PAUSE            = 5
PRICE_PRIMI          = 4.50
PRICE_SECONDI        = 5.50
PRICE_COFFEE         = 1.20
OVERLOAD_THRESHOLD   = 999
MENU_FILE            = conf/menu.txt
